version: '3'
services:
  simulator: 
    restart: "no"
    image: pkoperek/cloudsimplus-gateway:1.8.2
    environment:
      # sets the number of hosts in the datacenter
      # we assume that every host can hold 2+4+8 CPUs (so 1 vm of each type)
      - DATACENTER_HOSTS_CNT=18
    expose: 
      - "25333"

  sammdb:
    image: postgres:10
    environment:
      - POSTGRES_USER=samm
      - POSTGRES_PASSWORD=samm
      - POSTGRES_DB=samm
      - PGDATA=/storage
    volumes:
      - ./ignored/samm_pgdata:/storage
      - ./db_init/sammdb.sql:/docker-entrypoint-initdb.d/sammdb.sql
      - ./db_init/synthetic_metrics.sql:/docker-entrypoint-initdb.d/synthetic_metrics.sql
    ports:
      - "5432:5432"

  dnnevodb:
    image: postgres:10
    environment:
      - POSTGRES_USER=dnnevo
      - POSTGRES_PASSWORD=dnnevo
      - POSTGRES_DB=dnnevo
      - PGDATA=/storage
    volumes:
      - ./ignored/dnnevo_pgdata:/storage
      - ./db_init/dnnevodb.sql:/docker-entrypoint-initdb.d/dnnevodb.sql
      - ./db_init/synthetic_workload.sql:/docker-entrypoint-initdb.d/synthetic_workload.sql
    ports:
      - "5433:5432"
        
  driver:
    # image: amalota/trainloop-driver:1.3.6
    build: .
    environment:
      - CLOUDSIM_GATEWAY_HOST=simulator
      - CLOUDSIM_GATEWAY_PORT=25333
    # Parameters from 10MM
    command: ["trainloop",
              "--env", "ThreeSizeAppEnv-v1",
              "--num_env", "6",
              "--simulator_speedup", "60",
              "--queue_wait_penalty", "0.0005", # 0.00001
              "--save_path", "/output_models", 
              "--mips_per_core", "3600", 
              "--seed", "1",
              "--mips_per_core", "4400",
              "--log_path", "/logs",
              # "--vf_coef", "0.0005",
              # "--lam", "0.97",
              # "--gamma", "0.99",
              # "--cliprange", "0.2",
              "--num_timesteps", "12",  #25000 #10000  # this needs to be adjusted to the amount of data fetched from the db; 500k should be enough to train from fresh, but not too long in wall clock time
              "--n_steps", "256",  # 2048
              # "--lr", "0.0003",
              # "--network", "lstm",
              "--iteration_length_s", "11",  # 15 minutes per iteration # 900 #1800
              "--initial_timestamp", "0",
              "--initial_vm_count_no_data", "3",
              "--policy", "MlpPolicy", # MlpLstmPolicy, CnnLstmPolicy, MlpPolicy, CnnPolicy
              "--algo", "DQN", # DQN, PPO, RecurrentPPO
             "--initial_model", "True",
              "--nminibatches", "1", # to stop recurrent networks from breaking
              "--continuous_mode"]
    depends_on:
      - simulator
      - sammdb
      - dnnevodb
    volumes:
      - "./output_models:/output_models"
      - "./best_model:/best_model"
      - "./initial_model:/initial_model"
      - "./input_workloads:/input_workloads"
      - "./logs:/logs"
