version: '3'
services:
  simulator: 
    restart: "no"
    image: pkoperek/cloudsimplus-gateway:1.8.2
    environment:
      # sets the number of hosts in the datacenter
      # we assume that every host can hold 2+4+8 CPUs (so 1 vm of each type)
      # - DATACENTER_HOSTS_CNT=18
      - HOST_PE_MIPS=4400
      - MAX_VMS_PER_SIZE=10
    expose: 
      - "25333"

  sammdb:
    image: postgres:10
    environment:
      - POSTGRES_USER=samm
      - POSTGRES_PASSWORD=samm
      - POSTGRES_DB=samm
      - PGDATA=/storage
    volumes:
      - ./ignored/samm_pgdata:/storage
      - ./db_init/sammdb.sql:/docker-entrypoint-initdb.d/sammdb.sql
      - ./db_init/synthetic_metrics.sql:/docker-entrypoint-initdb.d/synthetic_metrics.sql
    ports:
      - "5432:5432"

  dnnevodb:
    image: postgres:10
    environment:
      - POSTGRES_USER=dnnevo
      - POSTGRES_PASSWORD=dnnevo
      - POSTGRES_DB=dnnevo
      - PGDATA=/storage
    volumes:
      - ./ignored/dnnevo_pgdata:/storage
      - ./db_init/dnnevodb.sql:/docker-entrypoint-initdb.d/dnnevodb.sql
      - ./db_init/synthetic_workload.sql:/docker-entrypoint-initdb.d/synthetic_workload.sql
    ports:
      - "5433:5432"
        
  evaluate_test_workload:
    # image: amalota/trainloop-driver:1.3.6
    build: .
    environment:
      - CLOUDSIM_GATEWAY_HOST=simulator
      - CLOUDSIM_GATEWAY_PORT=25333
    # Parameters from 10MM
    command: ["trainloop", 
              "--env", "ThreeSizeAppEnv-v1",
              "--num_env", "1",
              "--workload_file", "/input_workloads/TEST-DNNEVO-2.swf",
              "--simulator_speedup", "60",
              "--queue_wait_penalty", "0.0005", # 0.00001
              "--seed", "5",
              "--mips_per_core", "4400",
              "--log_path", "/logs",
              "--initial_vm_count_no_data", "3",
              "--evaluate_mode"]
    depends_on:
      - simulator
      - sammdb
      - dnnevodb
    volumes:
      # - "./output_models:/output_models"
      - "./initial_model:/initial_model"
      # - "./best_model:/best_model"
      - "./output_models_initial:/output_models_initial"
      - "./input_workloads:/input_workloads"
      - "./logs:/logs"
