version: '3'
services:
  simulator:
    restart: "no"
    environment:
      - HOST_PE_MIPS=4400
      - MAX_VMS_PER_SIZE=10
      - PRINT_JOBS_PERIODICALLY=false
    image: pkoperek/cloudsimplus-gateway:1.8.2

  driver_train_sample:
    build: .
    environment:
      - CLOUDSIM_GATEWAY_HOST=simulator
      - CLOUDSIM_GATEWAY_PORT=25333
    # remember to download and setup a training workload before starting
    # the training process!
    command: [
            "trainloop",
            "--simulator_speedup", "60",
            "--num_env", "6",  # 6
            "--mips_per_core", "4400",
            "--workload_file", "/input_workloads/TEST-DNNEVO-2.swf",
            "--env", "ThreeSizeAppEnv-v1",
            "--log_path", "/logs/20201026.1",
            "--num_timesteps", "2000000",  #  2000000
            "--nsteps", "100",  # PPO:2048, RecurrentPPO:128/256 change according to algo/policy or left default (have to uncomment in build_dqn/ppo_model())
            "--seed", "5",
            "--initial_vm_count", "1",
            "--nminibatches", "1",
            "--queue_wait_penalty", "0.0005",
            "--policy", "MlpLstmPolicy", # MlpLstmPolicy, CnnLstmPolicy, MlpPolicy, CnnPolicy
            "--algo", "RecurrentPPO", # DQN, PPO, RecurrentPPO
            ]
    depends_on:
      - simulator
    volumes:
      - "./training_logs:/logs"
      - "./output_models_initial:/output_models_initial"
      - "./initial_model:/initial_model"
      - "./input_workloads:/input_workloads"

